#!/usr/bin/env python

from front.FrontEnd import FrontEnd
from player.Player import Player
from curses import wrapper
from library.library import Library
from Exceptions.CLI_Audio_Exception import CLI_Audio_File_Exception
from Exceptions.CLI_Audio_Exception import CLI_Audio_Screen_Size_Exception

def main():
    player = Player()
    library = Library()
    front_end = FrontEnd(player, library)

if __name__ == "__main__":
    main()
